### ISSUE TITLE
Eroare la pornirea container-ului

### ISSUE THREAD

**Issue by Gabriela222** [Gabriela222/Licenta#2]
Tot nu pot trece mai departe.
Am aceasta eroare ,(cu fisierul de configurare in /home/template):

![image](https://user-images.githubusercontent.com/51826715/59551266-c2016280-8f7f-11e9-8c3f-517c515166a7.png)

Am deschis fisierul lxc_create.log si am vazut ca am aceste erori la crearea containerului :

invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.

Acestea am vazut ca mi se repeta si cand am rulat comanda de creare a containerului in masina virtuala de pe pc.

Am verificat si in directorul /etc/template si am user-ul "template"

[lxc_create.log](https://github.com/Gabriela222/Licenta/files/3292974/lxc_create.log)

Nu pot modifica https://github.com/midu16/VNFDiscovery/projects/1

**Comment by midu16** [comment]
in fisierul furnizat "lxc_create.log" am urmatorul mesaj 'Container already exists".

**Comment by Gabriela222** [comment]
Am tot incercat sa il generez de mai multe ori. Dar acele doua erori mi-au aparut in consola cand am creat container-ul 
 
  Pe sâm., iun. 15, 2019 la 16:03, Mihai I.<notifications@github.com> a scris:   
in fisierul furnizat "lxc_create.log" am urmatorul mesaj 'Container already exists".

**Comment by midu16** [comment]
> Am tot incercat sa il generez de mai multe ori. Dar acele doua erori mi-au aparut in consola cand am creat container-ul Pe sâm., iun. 15, 2019 la 16:03, Mihai I.<notifications@github.com> a scris: in fisierul furnizat "lxc_create.log" am urmatorul mesaj 'Container already exists". — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Incearca sa imi oferi output-ul de la "$lxc-ls ".

**Comment by Gabriela222** [comment]
nu imi afiseaza nimic
![image](https://user-images.githubusercontent.com/51826715/59551818-d9dce480-8f87-11e9-978e-3e14f6b21b85.png)

**Comment by Gabriela222** [comment]
[lxc_create.log](https://github.com/Gabriela222/Licenta/files/3293110/lxc_create.log)

acesta e primul fisier log creat

**Comment by Gabriela222** [comment]
acesta primul lxc creat

**Comment by Gabriela222** [comment]
![image](https://user-images.githubusercontent.com/51826715/59551947-c92d6e00-8f89-11e9-896d-5656a697adb5.png)

**Comment by midu16** [comment]
> ![image](https://user-images.githubusercontent.com/51826715/59551947-c92d6e00-8f89-11e9-896d-5656a697adb5.png)

$ sudo lxc-ls -f                                      - arata-mi care este output-ul la comanda asta. vreau sa vad care e healt-ul containerului.
$ sudo lxc-attach -n devstack               - cu comanda asta intri in bash-ul containerului.

**Comment by Gabriela222** [comment]
![image](https://user-images.githubusercontent.com/51826715/59552258-43abbd00-8f8d-11e9-9542-0515555dffa2.png)

**Comment by midu16** [comment]
> ![image](https://user-images.githubusercontent.com/51826715/59552258-43abbd00-8f8d-11e9-9542-0515555dffa2.png)

unde ai masina virtuala de pe cloud? 

Ca vad ca nu inaintam asa. Da-mi access pe ea si o sa fac eu.

**Comment by Gabriela222** [comment]
141.85.248.200
user :template
parola : Test12345#

**Comment by midu16** [comment]
@Gabriela222 vezi ca postul asta e public. informatiile astea nu sunt bune publicate chiar asa.

**Comment by Gabriela222** [comment]
le sterg acum
